#!/usr/bin/env python3

from pathlib import Path
import pandas as pd
import re
import gzip
import traceback
import os


# ============================================================
# CONFIGURATION
# ============================================================

TRIAL_ROOT = Path(os.environ.get("WORK_DIR", Path(__file__).resolve().parent)).resolve()

# DOI/GLIS resolver generated by your GLIS script
GLIS_OK_FILE = TRIAL_ROOT / "glis_gid_OK.tsv"

# Output directory
OUTDIR = TRIAL_ROOT / "metadata_outputs"
OUTDIR.mkdir(exist_ok=True)

# If empty, script will auto-discover HMP/VCF files under TRIAL_ROOT
HMP_FILES = []
VCF_FILES = []

# Phenotype-based GID recovery can be slow but useful
USE_PHENOTYPE_GID_RECOVERY = True

# Files used only as optional GID resolvers when FieldBook lacks GID
PHENO_RESOLVER_PATTERNS = [
    "*RawData*",
    "*MeanVal*",
    "*GrnYld*",
    "*Genotypes_Data*",
]


# ============================================================
# NORMALIZATION FUNCTIONS
# ============================================================

def norm_token(x):
    """
    Normalize a cell/column label for robust matching.
    Example: 'Cross Name' -> 'crossname'
    """
    if pd.isna(x):
        return ""
    x = str(x).strip().lower()
    x = re.sub(r"\s+", "", x)
    x = re.sub(r"[^a-z0-9]", "", x)
    return x


def clean_col(x):
    """
    Convert column label into a simple machine-friendly string.
    """
    if pd.isna(x):
        x = ""
    x = str(x).strip()
    x = re.sub(r"\s+", "_", x)
    x = x.replace("-", "_").replace("/", "_")
    x = re.sub(r"[^A-Za-z0-9_]", "", x)
    return x


def make_unique_columns(cols):
    """
    Avoid duplicated column names after cleaning.
    """
    seen = {}
    out = []

    for c in cols:
        base = clean_col(c)
        if base == "":
            base = "unnamed"

        if base not in seen:
            seen[base] = 0
            out.append(base)
        else:
            seen[base] += 1
            out.append(f"{base}_{seen[base]}")

    return out


def normalize_id(x):
    """
    Normalize numeric-like IDs.
    """
    if pd.isna(x):
        return pd.NA
    x = str(x).strip()
    x = re.sub(r"\.0$", "", x)
    if x.lower() in {"", "nan", "none", "<na>", "na"}:
        return pd.NA
    return x


def normalize_gid(x):
    """
    Normalize GID by removing optional GID prefix and Excel .0.
    """
    if pd.isna(x):
        return pd.NA
    x = str(x).strip()
    x = re.sub(r"^GID", "", x, flags=re.IGNORECASE)
    x = re.sub(r"\.0$", "", x)
    if x.lower() in {"", "nan", "none", "<na>", "na"}:
        return pd.NA
    return x


def missing_series(s):
    """
    Boolean mask for missing IDs in object/string columns.
    """
    ss = s.astype("string").str.strip().str.lower()
    return s.isna() | ss.isin(["", "nan", "none", "<na>", "na"])


def safe_read_excel_all_sheets(path):
    """
    Read all sheets from xlsx/xls workbook.
    """
    return pd.read_excel(path, sheet_name=None, header=None, dtype=str)


def read_table_auto_header0(path):
    """
    Read CIMMYT tab/csv/xls-like files with a real header row.
    Many .xls files are actually tab-delimited text.
    """
    path = Path(path)

    # Try delimiter inference first
    try:
        return pd.read_csv(
            path,
            sep=None,
            engine="python",
            dtype=str,
            encoding="latin1"
        )
    except Exception:
        pass

    # Try tab
    try:
        return pd.read_csv(
            path,
            sep="\t",
            dtype=str,
            encoding="latin1"
        )
    except Exception:
        pass

    # Try comma
    try:
        return pd.read_csv(
            path,
            sep=",",
            dtype=str,
            encoding="latin1"
        )
    except Exception:
        pass

    # Try Excel
    return pd.read_excel(path, dtype=str)


# ============================================================
# FIELDBOOK PARSING
# ============================================================

def find_header_row(raw):
    """
    Find header row requiring only CID and SID.
    GID is optional because some FieldBooks lack it.
    """
    for i in range(len(raw)):
        token_set = {norm_token(x) for x in raw.iloc[i].tolist()}

        if {"cid", "sid"}.issubset(token_set):
            return i

    return None


def extract_metadata(raw):
    """
    Extract trial-level metadata from the top rows of a FieldBook.
    """
    meta = {
        "trial_name": pd.NA,
        "trial_abbr": pd.NA,
        "cycle": pd.NA,
        "occ": pd.NA,
        "tid": pd.NA,
        "cooperator_id": pd.NA,
        "program": pd.NA,
    }

    key_map = {
        "trialname": "trial_name",
        "trialabbr": "trial_abbr",
        "cycle": "cycle",
        "occ": "occ",
        "tid": "tid",
        "cooperatorid": "cooperator_id",
        "program": "program",
    }

    for i in range(min(100, len(raw))):
        row = raw.iloc[i].tolist()

        for j, val in enumerate(row):
            key = norm_token(val)

            if key in key_map and j + 1 < len(row):
                meta[key_map[key]] = raw.iloc[i, j + 1]

    return meta


def standardize_fieldbook_columns(df):
    """
    Rename known FieldBook columns to canonical names.
    """
    rename = {}

    for c in df.columns:
        k = norm_token(c)

        if k == "cid":
            rename[c] = "CID"
        elif k == "sid":
            rename[c] = "SID"
        elif k == "gid":
            rename[c] = "fieldbook_gid"
        elif k == "crossname":
            rename[c] = "cross_name"
        elif k == "selectionhistory":
            rename[c] = "selection_history"
        elif k == "origin":
            rename[c] = "origin"
        elif k == "plot":
            rename[c] = "plot"
        elif k == "rep":
            rename[c] = "rep"
        elif k in {"subblock", "subbloque"}:
            rename[c] = "subblock"
        elif k == "entry":
            rename[c] = "entry"
        elif k == "row":
            rename[c] = "row"
        elif k in {"col", "column"}:
            rename[c] = "col"

    return df.rename(columns=rename)


def parse_fieldbook(path):
    """
    Parse one Empty_FieldBook workbook.

    Returns rows with at least CID and SID.
    GID is optional and stored as fieldbook_gid.
    """
    sheets = safe_read_excel_all_sheets(path)
    parsed = []

    for sheet_name, raw in sheets.items():
        header_row = find_header_row(raw)

        if header_row is None:
            continue

        meta = extract_metadata(raw)

        header = raw.iloc[header_row].tolist()
        data = raw.iloc[header_row + 1:].copy()
        data.columns = make_unique_columns(header)

        data = data.dropna(how="all")
        data = standardize_fieldbook_columns(data)

        if not {"CID", "SID"}.issubset(data.columns):
            continue

        if "fieldbook_gid" not in data.columns:
            data["fieldbook_gid"] = pd.NA

        keep = [
            c for c in [
                "CID", "SID", "fieldbook_gid", "cross_name",
                "selection_history", "origin", "plot", "rep",
                "subblock", "entry", "row", "col"
            ]
            if c in data.columns
        ]

        data = data[keep].copy()

        for col in ["CID", "SID", "fieldbook_gid", "plot", "rep", "subblock", "entry", "row", "col"]:
            if col in data.columns:
                data[col] = data[col].map(normalize_id)

        data["fieldbook_gid"] = data["fieldbook_gid"].map(normalize_gid)

        # Remove non-data rows
        data = data[~missing_series(data["CID"])]
        data = data[~missing_series(data["SID"])]

        if len(data) == 0:
            continue

        data["fieldbook_has_gid"] = ~missing_series(data["fieldbook_gid"])

        for k, v in meta.items():
            data[k] = v

        data["fieldbook_file"] = str(path)
        data["fieldbook_sheet"] = str(sheet_name)

        parsed.append(data)

    if not parsed:
        raise ValueError("No CID/SID table found in workbook")

    return pd.concat(parsed, ignore_index=True)


def discover_fieldbooks(root):
    """
    Find FieldBook files and exclude Excel temporary lock files.
    """
    files = list(root.rglob("*FieldBook*.xlsx")) + list(root.rglob("*FieldBook*.xls"))

    files = sorted(
        p for p in files
        if p.is_file() and not p.name.startswith("~$")
    )

    return files


def infer_trial_id_from_fieldbook(path):
    """
    Infer trial ID from filename.
    """
    name = Path(path).name
    name = re.sub(r"[-_ ]?Empty[_ ]?FieldBook.*$", "", name, flags=re.IGNORECASE)
    name = re.sub(r"\.xlsx?$", "", name, flags=re.IGNORECASE)
    return name.strip()


# ============================================================
# DOI FILE PARSING
# ============================================================

def standardize_doi_columns(df):
    df.columns = make_unique_columns(df.columns)

    rename = {}

    for c in df.columns:
        k = norm_token(c)

        if k == "cid":
            rename[c] = "CID"
        elif k == "sid":
            rename[c] = "SID"
        elif k == "gid":
            rename[c] = "doi_gid"
        elif k == "doi":
            rename[c] = "DOI"
        elif k in {"doiglisurl", "glisurl", "url"}:
            rename[c] = "DOI_GLIS_url"

    df = df.rename(columns=rename)

    keep = [c for c in ["CID", "SID", "doi_gid", "DOI", "DOI_GLIS_url"] if c in df.columns]
    df = df[keep].drop_duplicates()

    for col in ["CID", "SID", "doi_gid", "DOI"]:
        if col in df.columns:
            df[col] = df[col].map(normalize_id)

    if "doi_gid" in df.columns:
        df["doi_gid"] = df["doi_gid"].map(normalize_gid)

    if "DOI" in df.columns:
        df["DOI"] = df["DOI"].astype("string").str.strip()

    return df


def read_doi_file(path):
    df = read_table_auto_header0(path)
    return standardize_doi_columns(df)


def find_trial_doi_file(trial_dir):
    """
    Find Germplasm_DOIs file inside the trial folder.
    """
    hits = [
        p for p in Path(trial_dir).glob("*Germplasm_DOIs*")
        if p.is_file() and not p.name.startswith("~$")
    ]

    if not hits:
        return None

    # Prefer csv/tab over Excel temporary variants
    hits = sorted(hits)
    return hits[0]


def merge_doi_into_manifest(geno, trial_dir):
    """
    Merge trial Germplasm_DOIs into FieldBook genotype rows.
    DOI file is optional.
    """
    geno = geno.copy()

    geno["DOI"] = pd.NA
    geno["DOI_GLIS_url"] = pd.NA
    geno["doi_file"] = pd.NA
    geno["doi_merge_status"] = "no_doi_file"

    doi_file = find_trial_doi_file(trial_dir)

    if doi_file is None:
        return geno

    geno["doi_file"] = str(doi_file)

    try:
        doi = read_doi_file(doi_file)

        if {"CID", "SID"}.issubset(doi.columns):
            geno = geno.drop(columns=["DOI", "DOI_GLIS_url"], errors="ignore")

            geno = geno.merge(
                doi,
                on=["CID", "SID"],
                how="left",
                suffixes=("", "_doi")
            )

            geno["doi_merge_status"] = "merged_by_cid_sid"

        elif "doi_gid" in doi.columns and "fieldbook_gid" in geno.columns:
            geno = geno.drop(columns=["DOI", "DOI_GLIS_url"], errors="ignore")

            geno = geno.merge(
                doi,
                left_on="fieldbook_gid",
                right_on="doi_gid",
                how="left",
                suffixes=("", "_doi")
            )

            geno["doi_merge_status"] = "merged_by_gid"

        else:
            geno["doi_merge_status"] = "doi_file_without_linkable_keys"

    except Exception as e:
        geno["doi_merge_status"] = f"doi_parse_error: {e}"

    return geno


# ============================================================
# GLIS GID RESOLVER
# ============================================================

def load_glis_resolver(path):
    """
    Load glis_gid_OK.tsv with columns:
    DOI, GLIS_URL, GID, status, source_files
    """
    if not Path(path).exists():
        return pd.DataFrame(columns=["DOI", "glis_gid", "glis_url", "glis_status", "glis_source_files"])

    glis = pd.read_csv(path, sep="\t", dtype=str)
    glis.columns = [clean_col(c) for c in glis.columns]

    rename = {}
    for c in glis.columns:
        k = norm_token(c)

        if k == "doi":
            rename[c] = "DOI"
        elif k in {"glisurl", "url"}:
            rename[c] = "glis_url"
        elif k == "gid":
            rename[c] = "glis_gid"
        elif k == "status":
            rename[c] = "glis_status"
        elif k == "sourcefiles":
            rename[c] = "glis_source_files"

    glis = glis.rename(columns=rename)

    keep = [c for c in ["DOI", "glis_gid", "glis_url", "glis_status", "glis_source_files"] if c in glis.columns]
    glis = glis[keep].drop_duplicates()

    if "DOI" in glis.columns:
        glis["DOI"] = glis["DOI"].astype("string").str.strip()

    if "glis_gid" in glis.columns:
        glis["glis_gid"] = glis["glis_gid"].map(normalize_gid)

    return glis


def apply_glis_resolver(manifest, glis):
    """
    Merge GLIS DOI resolver and fill missing GIDs.
    """
    manifest = manifest.copy()

    if glis is None or len(glis) == 0 or "DOI" not in manifest.columns:
        manifest["glis_gid"] = pd.NA
        manifest["glis_url"] = pd.NA
        manifest["glis_status"] = pd.NA
        return manifest

    manifest["DOI"] = manifest["DOI"].astype("string").str.strip()
    glis["DOI"] = glis["DOI"].astype("string").str.strip()

    manifest = manifest.merge(
        glis,
        on="DOI",
        how="left"
    )

    return manifest


# ============================================================
# OPTIONAL PHENOTYPE-BASED GID RECOVERY
# ============================================================

def standardize_generic_trial_columns(df):
    df.columns = make_unique_columns(df.columns)

    rename = {}

    for c in df.columns:
        k = norm_token(c)

        if k == "cid":
            rename[c] = "CID"
        elif k == "sid":
            rename[c] = "SID"
        elif k == "gid":
            rename[c] = "pheno_gid"
        elif k == "trialname":
            rename[c] = "trial_name_in_file"
        elif k == "cycle":
            rename[c] = "cycle_in_file"
        elif k == "occ":
            rename[c] = "occ_in_file"
        elif k in {"locno", "locationno"}:
            rename[c] = "loc_no_in_file"

    df = df.rename(columns=rename)
    return df


def extract_gid_resolver_from_trial_file(path):
    """
    Extract CID/SID/GID mapping from RawData, MeanVal, GrnYld,
    or Genotypes_Data if available.
    """
    try:
        df = read_table_auto_header0(path)
    except Exception:
        return pd.DataFrame(columns=["CID", "SID", "pheno_gid", "pheno_gid_source_file"])

    df = standardize_generic_trial_columns(df)

    if not {"CID", "SID", "pheno_gid"}.issubset(df.columns):
        return pd.DataFrame(columns=["CID", "SID", "pheno_gid", "pheno_gid_source_file"])

    out = df[["CID", "SID", "pheno_gid"]].copy()

    for col in ["CID", "SID", "pheno_gid"]:
        out[col] = out[col].map(normalize_id)

    out["pheno_gid"] = out["pheno_gid"].map(normalize_gid)

    out = out[~missing_series(out["CID"])]
    out = out[~missing_series(out["SID"])]
    out = out[~missing_series(out["pheno_gid"])]

    out = out.drop_duplicates()
    out["pheno_gid_source_file"] = str(path)

    return out


def build_pheno_gid_resolver_for_dir(trial_dir):
    """
    Build CID/SID -> GID resolver from phenotype/genotype tables in a trial directory.
    """
    trial_dir = Path(trial_dir)

    files = []
    for pattern in PHENO_RESOLVER_PATTERNS:
        files.extend(trial_dir.glob(pattern))

    files = sorted(
        p for p in set(files)
        if p.is_file() and not p.name.startswith("~$")
    )

    dfs = []

    for f in files:
        r = extract_gid_resolver_from_trial_file(f)
        if len(r) > 0:
            dfs.append(r)

    if not dfs:
        return pd.DataFrame(columns=["CID", "SID", "pheno_gid", "pheno_gid_source_file", "pheno_gid_conflict"])

    resolver = pd.concat(dfs, ignore_index=True).drop_duplicates()

    # Detect conflicts: same CID/SID mapping to multiple GIDs
    conflict_counts = (
        resolver
        .groupby(["CID", "SID"])["pheno_gid"]
        .nunique()
        .reset_index(name="n_pheno_gid")
    )

    resolver = resolver.merge(conflict_counts, on=["CID", "SID"], how="left")
    resolver["pheno_gid_conflict"] = resolver["n_pheno_gid"] > 1

    # Keep only non-conflicting resolver rows
    clean = resolver[resolver["pheno_gid_conflict"] == False].copy()
    clean = clean.drop_duplicates(subset=["CID", "SID", "pheno_gid"])

    # If multiple source files agree, keep first
    clean = clean.sort_values(["CID", "SID", "pheno_gid_source_file"])
    clean = clean.drop_duplicates(subset=["CID", "SID"], keep="first")

    return clean[["CID", "SID", "pheno_gid", "pheno_gid_source_file", "pheno_gid_conflict"]]


def apply_pheno_gid_recovery(manifest):
    """
    Fill unresolved GIDs using trial files that contain CID/SID/GID.
    """
    manifest = manifest.copy()

    manifest["pheno_gid"] = pd.NA
    manifest["pheno_gid_source_file"] = pd.NA
    manifest["pheno_gid_conflict"] = pd.NA

    unresolved = missing_series(manifest["resolved_gid"])

    if unresolved.sum() == 0:
        return manifest

    trial_dirs = sorted(manifest.loc[unresolved, "trial_dir"].dropna().unique())

    all_resolvers = []

    for td in trial_dirs:
        resolver = build_pheno_gid_resolver_for_dir(td)

        if len(resolver) > 0:
            resolver["trial_dir"] = td
            all_resolvers.append(resolver)

    if not all_resolvers:
        return manifest

    resolver_all = pd.concat(all_resolvers, ignore_index=True).drop_duplicates()

    manifest = manifest.merge(
        resolver_all,
        on=["trial_dir", "CID", "SID"],
        how="left",
        suffixes=("", "_resolver")
    )

    # Resolve duplicate column names if they appear
    if "pheno_gid_resolver" in manifest.columns:
        manifest["pheno_gid"] = manifest["pheno_gid_resolver"]
        manifest = manifest.drop(columns=["pheno_gid_resolver"], errors="ignore")

    missing_gid = missing_series(manifest["resolved_gid"])
    has_pheno_gid = ~missing_series(manifest["pheno_gid"])

    fill_mask = missing_gid & has_pheno_gid

    manifest.loc[fill_mask, "resolved_gid"] = manifest.loc[fill_mask, "pheno_gid"]
    manifest.loc[fill_mask, "gid_source"] = "phenotype_table_cid_sid"

    return manifest


# ============================================================
# GID RESOLUTION
# ============================================================

def resolve_gid(manifest):
    """
    Create resolved_gid from:
    1. fieldbook_gid
    2. glis_gid
    3. phenotype tables later
    """
    manifest = manifest.copy()

    if "glis_gid" not in manifest.columns:
        manifest["glis_gid"] = pd.NA

    manifest["resolved_gid"] = pd.NA
    manifest["gid_source"] = "unresolved"

    has_fieldbook_gid = ~missing_series(manifest["fieldbook_gid"])
    has_glis_gid = ~missing_series(manifest["glis_gid"])

    manifest.loc[has_fieldbook_gid, "resolved_gid"] = manifest.loc[has_fieldbook_gid, "fieldbook_gid"]
    manifest.loc[has_fieldbook_gid, "gid_source"] = "fieldbook"

    fill_from_glis = missing_series(manifest["resolved_gid"]) & has_glis_gid
    manifest.loc[fill_from_glis, "resolved_gid"] = manifest.loc[fill_from_glis, "glis_gid"]
    manifest.loc[fill_from_glis, "gid_source"] = "glis_doi_resolver"

    # Conflict detection
    manifest["fieldbook_glis_gid_conflict"] = (
        has_fieldbook_gid
        & has_glis_gid
        & (manifest["fieldbook_gid"].astype(str) != manifest["glis_gid"].astype(str))
    )

    manifest["gid_resolution_status"] = "resolved"
    manifest.loc[missing_series(manifest["resolved_gid"]), "gid_resolution_status"] = "unresolved_no_gid"
    manifest.loc[manifest["fieldbook_glis_gid_conflict"], "gid_resolution_status"] = "fieldbook_glis_gid_conflict"

    manifest["panel_sample_id_expected"] = pd.NA
    has_resolved = ~missing_series(manifest["resolved_gid"])
    manifest.loc[has_resolved, "panel_sample_id_expected"] = (
        "GID" + manifest.loc[has_resolved, "resolved_gid"].astype(str)
    )

    return manifest


# ============================================================
# PANEL SAMPLE PARSING: HMP AND VCF
# ============================================================

def open_maybe_gzip(path):
    path = str(path)
    if path.endswith(".gz"):
        return gzip.open(path, "rt")
    return open(path, "r")


def discover_hmp_files(root):
    patterns = [
        "*.hmp",
        "*.hmp.txt",
        "*.hmp.txt.gz",
        "*.hmp.gz",
        "*hmp*",
    ]

    files = []
    for pattern in patterns:
        files.extend(Path(root).rglob(pattern))

    files = sorted(
        p for p in set(files)
        if p.is_file()
        and not p.name.startswith("~$")
        and not p.name.endswith(".tsv")
        and not p.name.endswith(".csv")
    )

    return files


def discover_vcf_files(root):
    patterns = [
        "*.vcf",
        "*.vcf.gz",
    ]

    files = []
    for pattern in patterns:
        files.extend(Path(root).rglob(pattern))

    files = sorted(
        p for p in set(files)
        if p.is_file() and not p.name.startswith("~$")
    )

    return files


def extract_gid_from_sample(sample_id):
    """
    Extract numeric GID from sample name.
    Accepts:
        GID123456
        GID123456_1
        123456
    """
    if pd.isna(sample_id):
        return pd.NA

    s = str(sample_id).strip()

    m = re.search(r"GID(\d+)", s, flags=re.IGNORECASE)
    if m:
        return m.group(1)

    if re.fullmatch(r"\d+", s):
        return s

    return pd.NA


def parse_hmp_samples(path):
    """
    HapMap: first 11 columns are metadata, then sample IDs.
    """
    try:
        with open_maybe_gzip(path) as f:
            header = f.readline().rstrip("\n").split("\t")
    except Exception as e:
        return pd.DataFrame([{
            "panel_file": str(path),
            "panel_type": "HMP",
            "panel_parse_status": f"hmp_read_error: {e}",
            "panel_sample_id": pd.NA,
            "panel_gid": pd.NA,
        }])

    if len(header) <= 11:
        return pd.DataFrame([{
            "panel_file": str(path),
            "panel_type": "HMP",
            "panel_parse_status": "hmp_header_too_short",
            "panel_sample_id": pd.NA,
            "panel_gid": pd.NA,
        }])

    samples = header[11:]

    df = pd.DataFrame({"panel_sample_id": samples})
    df["panel_gid"] = df["panel_sample_id"].map(extract_gid_from_sample)
    df["panel_file"] = str(path)
    df["panel_type"] = "HMP"

    name = Path(path).name.lower()
    if "unimputed" in name:
        df["imputation_status"] = "unimputed"
    elif "imputed" in name:
        df["imputation_status"] = "imputed"
    else:
        df["imputation_status"] = pd.NA

    df["panel_parse_status"] = "ok"

    return df


def parse_vcf_samples(path):
    """
    VCF: sample IDs are after FORMAT in #CHROM header line.
    """
    samples = None

    try:
        with open_maybe_gzip(path) as f:
            for line in f:
                if line.startswith("#CHROM"):
                    parts = line.rstrip("\n").split("\t")
                    if len(parts) > 9:
                        samples = parts[9:]
                    else:
                        samples = []
                    break
    except Exception as e:
        return pd.DataFrame([{
            "panel_file": str(path),
            "panel_type": "VCF",
            "panel_parse_status": f"vcf_read_error: {e}",
            "panel_sample_id": pd.NA,
            "panel_gid": pd.NA,
        }])

    if samples is None:
        return pd.DataFrame([{
            "panel_file": str(path),
            "panel_type": "VCF",
            "panel_parse_status": "no_chrom_header",
            "panel_sample_id": pd.NA,
            "panel_gid": pd.NA,
        }])

    df = pd.DataFrame({"panel_sample_id": samples})
    df["panel_gid"] = df["panel_sample_id"].map(extract_gid_from_sample)
    df["panel_file"] = str(path)
    df["panel_type"] = "VCF"
    df["imputation_status"] = pd.NA
    df["panel_parse_status"] = "ok"

    return df


def build_panel_sample_manifest(root):
    if HMP_FILES:
        hmp_files = [Path(x) for x in HMP_FILES]
    else:
        hmp_files = discover_hmp_files(root)

    if VCF_FILES:
        vcf_files = [Path(x) for x in VCF_FILES]
    else:
        vcf_files = discover_vcf_files(root)

    dfs = []

    for hmp in hmp_files:
        dfs.append(parse_hmp_samples(hmp))

    for vcf in vcf_files:
        dfs.append(parse_vcf_samples(vcf))

    if not dfs:
        return pd.DataFrame(columns=[
            "panel_sample_id", "panel_gid", "panel_file",
            "panel_type", "imputation_status", "panel_parse_status"
        ])

    panel = pd.concat(dfs, ignore_index=True)

    panel = panel[~missing_series(panel["panel_sample_id"])]
    panel = panel.drop_duplicates()

    return panel


def match_manifest_to_panel(manifest, panel):
    manifest = manifest.copy()

    if len(panel) == 0:
        manifest["panel_sample_id"] = pd.NA
        manifest["panel_file"] = pd.NA
        manifest["panel_type"] = pd.NA
        manifest["imputation_status"] = pd.NA
        manifest["panel_match_status"] = "no_panel_files_found"
        return manifest

    matched = manifest.merge(
        panel,
        left_on="resolved_gid",
        right_on="panel_gid",
        how="left"
    )

    matched["panel_match_status"] = "no_panel_match"

    unresolved = missing_series(matched["resolved_gid"])
    has_panel = ~missing_series(matched["panel_sample_id"])

    matched.loc[unresolved, "panel_match_status"] = "unresolved_no_gid"

    matched.loc[
        has_panel
        & (matched["panel_sample_id"].astype(str) == matched["panel_sample_id_expected"].astype(str)),
        "panel_match_status"
    ] = "exact_gid_panel_match"

    matched.loc[
        has_panel
        & (matched["panel_sample_id"].astype(str) != matched["panel_sample_id_expected"].astype(str)),
        "panel_match_status"
    ] = "gid_match_noncanonical_sample_or_suffix"

    return matched


# ============================================================
# DIAGNOSTICS
# ============================================================

def build_fieldbook_header_diagnostics(fieldbook_files):
    rows = []

    for fb in fieldbook_files:
        try:
            sheets = safe_read_excel_all_sheets(fb)
        except Exception as e:
            rows.append({
                "file": str(fb),
                "status": "read_error",
                "n_hits": 0,
                "first_hit": "",
                "error": str(e)
            })
            continue

        hits = []

        for sheet_name, raw in sheets.items():
            for i in range(min(120, len(raw))):
                token_set = {norm_token(x) for x in raw.iloc[i].tolist()}
                has_cid = "cid" in token_set
                has_sid = "sid" in token_set
                has_gid = "gid" in token_set

                if has_cid or has_sid or has_gid:
                    row_preview = " | ".join(raw.iloc[i].dropna().astype(str).tolist())
                    hits.append({
                        "sheet": sheet_name,
                        "row": i,
                        "has_cid": has_cid,
                        "has_sid": has_sid,
                        "has_gid": has_gid,
                        "row_preview": row_preview[:500]
                    })

        if hits:
            rows.append({
                "file": str(fb),
                "status": "header_candidates_found",
                "n_hits": len(hits),
                "first_hit": hits[0]["row_preview"],
                "error": ""
            })
        else:
            rows.append({
                "file": str(fb),
                "status": "no_header_candidates",
                "n_hits": 0,
                "first_hit": "",
                "error": ""
            })

    return pd.DataFrame(rows)


def write_summary(manifest, panel, matched, failed):
    summary_lines = []

    summary_lines.append("=== FIELDBOOK / GID MANIFEST SUMMARY ===")
    summary_lines.append(f"Rows in resolved manifest: {len(manifest)}")
    summary_lines.append(f"Unique resolved GIDs: {manifest['resolved_gid'].nunique(dropna=True)}")
    summary_lines.append(f"Unique fieldbook GIDs: {manifest['fieldbook_gid'].nunique(dropna=True)}")
    summary_lines.append(f"Unique GLIS GIDs: {manifest['glis_gid'].nunique(dropna=True) if 'glis_gid' in manifest.columns else 0}")
    summary_lines.append(f"Failed FieldBooks: {len(failed)}")

    summary_lines.append("\nGID resolution status:")
    summary_lines.append(str(manifest["gid_resolution_status"].value_counts(dropna=False)))

    summary_lines.append("\nGID source:")
    summary_lines.append(str(manifest["gid_source"].value_counts(dropna=False)))

    if "doi_merge_status" in manifest.columns:
        summary_lines.append("\nDOI merge status:")
        summary_lines.append(str(manifest["doi_merge_status"].value_counts(dropna=False)))

    summary_lines.append("\n=== PANEL SUMMARY ===")
    summary_lines.append(f"Panel sample rows: {len(panel)}")
    if len(panel) > 0:
        summary_lines.append(f"Unique panel GIDs: {panel['panel_gid'].nunique(dropna=True)}")
        summary_lines.append("Panel type counts:")
        summary_lines.append(str(panel["panel_type"].value_counts(dropna=False)))

    summary_lines.append("\n=== MATCH SUMMARY ===")
    summary_lines.append(str(matched["panel_match_status"].value_counts(dropna=False)))

    text = "\n".join(summary_lines)

    with open(OUTDIR / "summary.txt", "w") as f:
        f.write(text)

    print(text)


# ============================================================
# MAIN PIPELINE
# ============================================================

def main():
    print(f"Trial root: {TRIAL_ROOT}")
    print(f"Output directory: {OUTDIR}")

    # ------------------------------------------------------------
    # 1. Discover FieldBooks
    # ------------------------------------------------------------
    fieldbook_files = discover_fieldbooks(TRIAL_ROOT)
    print(f"FieldBooks found: {len(fieldbook_files)}")

    diagnostics = build_fieldbook_header_diagnostics(fieldbook_files)
    diagnostics.to_csv(OUTDIR / "fieldbook_header_diagnostics.tsv", sep="\t", index=False)

    # ------------------------------------------------------------
    # 2. Parse FieldBooks and merge trial DOI files
    # ------------------------------------------------------------
    all_manifest = []
    failed = []

    for fb in fieldbook_files:
        try:
            trial_dir = fb.parent
            trial_id = infer_trial_id_from_fieldbook(fb)

            geno = parse_fieldbook(fb)

            geno["trial_id"] = trial_id
            geno["trial_dir"] = str(trial_dir)

            # Deduplicate replicated plot rows while preserving unique entries
            dedup_keys = [
                c for c in [
                    "trial_id", "CID", "SID", "fieldbook_gid", "entry"
                ]
                if c in geno.columns
            ]

            geno = geno.drop_duplicates(subset=dedup_keys).copy()

            # Merge trial DOI file if possible
            geno = merge_doi_into_manifest(geno, trial_dir)

            all_manifest.append(geno)

        except Exception as e:
            failed.append({
                "fieldbook_file": str(fb),
                "stage": "fieldbook_parse_or_doi_merge",
                "error": str(e),
                "traceback": traceback.format_exc(limit=2)
            })

            print(f"ERROR parsing {fb}: {e}")

    failed_df = pd.DataFrame(
        failed,
        columns=["fieldbook_file", "stage", "error", "traceback"]
    )
    failed_df.to_csv(OUTDIR / "failed_fieldbooks.tsv", sep="\t", index=False)

    if not all_manifest:
        print("No FieldBooks were parsed. Check:")
        print(OUTDIR / "fieldbook_header_diagnostics.tsv")
        print(OUTDIR / "failed_fieldbooks.tsv")
        return

    manifest = pd.concat(all_manifest, ignore_index=True)

    # ------------------------------------------------------------
    # 3. Merge GLIS resolver and resolve GIDs
    # ------------------------------------------------------------
    glis = load_glis_resolver(GLIS_OK_FILE)
    glis.to_csv(OUTDIR / "clean_glis_gid_OK.tsv", sep="\t", index=False)

    manifest = apply_glis_resolver(manifest, glis)
    manifest = resolve_gid(manifest)

    # ------------------------------------------------------------
    # 4. Optional recovery from phenotype/genotype files
    # ------------------------------------------------------------
    if USE_PHENOTYPE_GID_RECOVERY:
        manifest = apply_pheno_gid_recovery(manifest)

        # Recompute status after phenotype recovery
        manifest["panel_sample_id_expected"] = pd.NA
        has_resolved = ~missing_series(manifest["resolved_gid"])
        manifest.loc[has_resolved, "panel_sample_id_expected"] = (
            "GID" + manifest.loc[has_resolved, "resolved_gid"].astype(str)
        )

        manifest["gid_resolution_status"] = "resolved"
        manifest.loc[
            missing_series(manifest["resolved_gid"]),
            "gid_resolution_status"
        ] = "unresolved_no_gid"

        conflict_mask = (
            (~missing_series(manifest["fieldbook_gid"]))
            & (~missing_series(manifest["glis_gid"]))
            & (manifest["fieldbook_gid"].astype(str) != manifest["glis_gid"].astype(str))
        )

        manifest.loc[
            conflict_mask,
            "gid_resolution_status"
        ] = "fieldbook_glis_gid_conflict"

    # ------------------------------------------------------------
    # 5. Final deduplication
    # ------------------------------------------------------------
    final_dedup_keys = [
        c for c in [
            "trial_id", "CID", "SID", "resolved_gid", "entry"
        ]
        if c in manifest.columns
    ]

    manifest = manifest.drop_duplicates(subset=final_dedup_keys).copy()

    # ------------------------------------------------------------
    # 6. Build HMP/VCF panel sample manifest
    # ------------------------------------------------------------
    panel = build_panel_sample_manifest(TRIAL_ROOT)

    # ------------------------------------------------------------
    # 7. Match resolved trial GIDs to panel samples
    # ------------------------------------------------------------
    matched = match_manifest_to_panel(manifest, panel)

    # ------------------------------------------------------------
    # 8. Write outputs
    # ------------------------------------------------------------
    manifest.to_csv(
        OUTDIR / "all_trials_genotype_manifest_resolved.tsv",
        sep="\t",
        index=False
    )

    panel.to_csv(
        OUTDIR / "panel_sample_manifest.tsv",
        sep="\t",
        index=False
    )

    matched.to_csv(
        OUTDIR / "final_trial_to_panel_matches.tsv",
        sep="\t",
        index=False
    )

    # QC subsets
    manifest[manifest["gid_resolution_status"] == "unresolved_no_gid"].to_csv(
        OUTDIR / "qc_unresolved_no_gid.tsv",
        sep="\t",
        index=False
    )

    manifest[manifest["gid_resolution_status"] == "fieldbook_glis_gid_conflict"].to_csv(
        OUTDIR / "qc_fieldbook_glis_gid_conflicts.tsv",
        sep="\t",
        index=False
    )

    matched[matched["panel_match_status"] == "no_panel_match"].to_csv(
        OUTDIR / "qc_resolved_gid_not_in_panel.tsv",
        sep="\t",
        index=False
    )

    matched[matched["panel_match_status"].isin([
        "exact_gid_panel_match",
        "gid_match_noncanonical_sample_or_suffix"
    ])].to_csv(
        OUTDIR / "usable_trial_to_panel_matches.tsv",
        sep="\t",
        index=False
    )

    write_summary(manifest, panel, matched, failed)

    print("\nOutputs written to:")
    print(f"  {OUTDIR / 'all_trials_genotype_manifest_resolved.tsv'}")
    print(f"  {OUTDIR / 'panel_sample_manifest.tsv'}")
    print(f"  {OUTDIR / 'final_trial_to_panel_matches.tsv'}")
    print(f"  {OUTDIR / 'usable_trial_to_panel_matches.tsv'}")
    print(f"  {OUTDIR / 'qc_unresolved_no_gid.tsv'}")
    print(f"  {OUTDIR / 'qc_fieldbook_glis_gid_conflicts.tsv'}")
    print(f"  {OUTDIR / 'qc_resolved_gid_not_in_panel.tsv'}")
    print(f"  {OUTDIR / 'failed_fieldbooks.tsv'}")
    print(f"  {OUTDIR / 'summary.txt'}")


if __name__ == "__main__":
    main()
